// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVMx8Bj1XStPS1jIcCY4tijvANgQiitE',
    appId: '1:603717884011:web:ca80ec65346a98a0ccf92e',
    messagingSenderId: '603717884011',
    projectId: 'nijyu-a1e04',
    authDomain: 'nijyu-a1e04.firebaseapp.com',
    databaseURL: 'https://nijyu-a1e04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nijyu-a1e04.appspot.com',
    measurementId: 'G-GSMMDJ8TCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd6pmDCFGGVZIAPad4qUWEweApW5-2aEU',
    appId: '1:603717884011:android:15d4864b543f41ecccf92e',
    messagingSenderId: '603717884011',
    projectId: 'nijyu-a1e04',
    databaseURL: 'https://nijyu-a1e04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nijyu-a1e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedo_bfKsDwf-72iT2H786IpE2R3Gdvwg',
    appId: '1:603717884011:ios:d29ce772153440feccf92e',
    messagingSenderId: '603717884011',
    projectId: 'nijyu-a1e04',
    databaseURL: 'https://nijyu-a1e04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nijyu-a1e04.appspot.com',
    iosClientId: '603717884011-nilm288sej9t1mli6ni8o9p3ugtpbi04.apps.googleusercontent.com',
    iosBundleId: 'com.example.nijyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCedo_bfKsDwf-72iT2H786IpE2R3Gdvwg',
    appId: '1:603717884011:ios:d29ce772153440feccf92e',
    messagingSenderId: '603717884011',
    projectId: 'nijyu-a1e04',
    databaseURL: 'https://nijyu-a1e04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nijyu-a1e04.appspot.com',
    iosClientId: '603717884011-nilm288sej9t1mli6ni8o9p3ugtpbi04.apps.googleusercontent.com',
    iosBundleId: 'com.example.nijyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFVMx8Bj1XStPS1jIcCY4tijvANgQiitE',
    appId: '1:603717884011:web:ca80ec65346a98a0ccf92e',
    messagingSenderId: '603717884011',
    projectId: 'nijyu-a1e04',
    authDomain: 'nijyu-a1e04.firebaseapp.com',
    databaseURL: 'https://nijyu-a1e04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nijyu-a1e04.appspot.com',
    measurementId: 'G-GSMMDJ8TCC',
  );

}